#v1.0 copyright Comine.com 20120119R2200
#
#
OUTPUT=MWakeOnLan.exe
CC=g++
COMPARGS= 
LINKARGS= -lgdi32 -luser32 -lkernel32


####################################################
all :
	$(CC) *.cpp -o $(OUTPUT) $(COMPARGS) $(LINKARGS) 
	


####################################################
clean:
	-rm -f *.o
	-rm -f $(OUTPUT)



####################################################
cleanall:
	-rm -f *.o
	-rm -f $(OUTPUT)


